apiVersion: v1
kind: Service
metadata:
  name: server
  labels:
    app: server
    app.kubernetes.io/name: server
    app.kubernetes.io/instance: server-1
    app.kubernetes.io/component: server
    app.kubernetes.io/part-of: kotlin-grpc-xds
spec:
  selector:
    app: server
    app.kubernetes.io/name: server
    app.kubernetes.io/instance: server-1
    app.kubernetes.io/component: server
    app.kubernetes.io/part-of: kotlin-grpc-xds
  ports:
    - protocol: TCP
      port: 8443
