apiVersion: apps/v1
kind: Deployment
metadata:
  name: client
  labels:
    app: client
spec:
  replicas: 2
  selector:
    matchLabels:
      app: client
  template:
    metadata:
      name: client
      labels:
        app: client
      annotations:
        inject.istio.io/templates: grpc-agent
    spec:
      containers:
        - name: client
          image: client:latest
          env:
            - name: TARGET_URL
              value: xds:///server:8443
